#!/bin/bash
github_username="philopaterwaheed"
github_password="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"
github_repository="simple_shell"
commit_message="commit_message"

git add .

# commit the changes with the commit message
git commit -m "commit_message"

# push the changes to the remote repository using the credentials
git push "https://${github_username}:${github_password}@github.com/${github_username}/${github_repository}.git" 
